version: '3.4'
services:
  gitdiff:
    container_name: gitdiff
    build:
      context: gitdiff/
    command: bash -c "python /app/manage.py makemigrations app && python /app/manage.py migrate --noinput && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./gitdiff/:/usr/src/app/
      - ./gitdiff/tmp/:/app/tmp/
    ports:
      - 8000:8000
    env_file:
      - envs/backend.env
    restart:
      on-failure
    networks:
      - gitlab_net
      - front_back
    links:
      - redis
    depends_on:
      - redis
      - redis_gitdiff

  frontend:
    build:
      context: frontend/
    ports:
      - 80:80
    depends_on:
      - gitdiff
    restart:
      on-failure
    networks:
      - front_back

  redis_gitdiff:
    container_name: redis_gitdiff
    image: "redis:alpine"
    networks:
      - front_back

  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - front_back

  celery:
    build:
      context: gitdiff/
    command: celery -A gitdiff worker -l info
    volumes:
      - ./gitdiff/:/usr/src/app/
      - ./gitdiff/tmp/:/app/tmp/
    depends_on:
      - redis
    networks:
      - front_back
      - gitlab_net
    links:
      - redis

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        external_url 'http://gitlab.example.com:443'
    ports:
      - '81:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./gitlab/etc/gitlab:/etc/gitlab
      - ./gitlab/var/opt/gitlab:/var/opt/gitlab
      - ./gitlab/var/log/gitlab:/var/log/gitlab
    shm_size: '256m'
    networks:
      - gitlab_net

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./gitlab/etc/gitlab-runner:/etc/gitlab-runner
      - ./gitlab/var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_net

networks:
  gitlab_net:
  front_back:

